version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_taskly
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskly_db
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
